arch: ResNet50
batch_size: 100
data: cifar
encoder_ckpt: '../pretrained/simclr-cifar10/checkpoint-48000.pth.tar'
imagenet_ckpt: '../inet32/checkpoint_7383943.pth.tar'
eval_freq: 245
iters: 58800
log_freq: 245
lr: 0.01
lr_schedule: warmup-anneal
opt: sgd
test_bs: 100
warmup: 0.01
weight_decay: 0.0001
workers: 2