arch: ResNet50
batch_size: 32
data: clothing
encoder_ckpt: '/home/arighosh/models/simclr-clothing/checkpoint-182600.pth.tar' 
eval_freq: 500
iters: 240000
log_freq: 500
momentum: 0.9
lr_schedule: step
step_size: 40000
gamma: 0.5
opt: sgd
#problem: finetune
test_bs: 100
warmup: 0.01
weight_decay: 0.001
workers: 4
scale_lower: 0.08
lr: 0.001
#loss: 'qloss'